import '@/styles/globals.css'
import type { Metadata } from 'next'
import { font } from '@/styles/font'

export const metadata: Metadata = {
  title: 'Base Apparel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
